// <auto-generated />
using System;
using BackendParaPlataforma.Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendParaPlataforma.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402102609_CrearAnalisisIADiarioReflexionUsuario")]
    partial class CrearAnalisisIADiarioReflexionUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnalisisIA", b =>
                {
                    b.Property<int>("Id_Analisis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Analisis"));

                    b.Property<bool>("Coincide_Usuario")
                        .HasColumnType("bit");

                    b.Property<decimal>("Confianza")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("Emocion_Detectada_IA")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Analisis")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Diario")
                        .HasColumnType("int");

                    b.Property<string>("Tono_Detectado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Analisis");

                    b.HasIndex("Emocion_Detectada_IA");

                    b.HasIndex("Id_Diario")
                        .IsUnique();

                    b.ToTable("analisis_ia", (string)null);
                });

            modelBuilder.Entity("BackendParaPlataforma.Entities.DiarioEmocional", b =>
                {
                    b.Property<int>("Id_Diario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Diario"));

                    b.Property<string>("Audio_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Creacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Id_Emocion_Usuario")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Texto_Usuario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id_Diario");

                    b.HasIndex("Id_Emocion_Usuario");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("diarios_emocionales", (string)null);
                });

            modelBuilder.Entity("BackendParaPlataforma.Entities.Emociones", b =>
                {
                    b.Property<int>("IdEmocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmocion"));

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Valor")
                        .IsRequired()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdEmocion");

                    b.ToTable("Emociones", (string)null);
                });

            modelBuilder.Entity("BackendParaPlataforma.Entities.ProgresoModuloUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completado")
                        .HasColumnType("bit");

                    b.Property<int>("IdModulo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("UltimaLeccion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario", "IdModulo")
                        .IsUnique();

                    b.ToTable("ProgresoModuloUsuario", (string)null);
                });

            modelBuilder.Entity("BackendParaPlataforma.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("ConfiguracionVoz")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("configuracion_voz");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("EstadoActual")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("estado_actual");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimo_login");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ProgresoUsuario", b =>
                {
                    b.Property<int>("Id_Progreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Progreso"));

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Porcentaje")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ultima_Actualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_Progreso");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("progreso_usuario", (string)null);
                });

            modelBuilder.Entity("ReflexionMejora", b =>
                {
                    b.Property<int>("Id_Reflexion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Reflexion"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Diario")
                        .HasColumnType("int");

                    b.Property<string>("Texto_Reflexion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id_Reflexion");

                    b.HasIndex("Id_Diario")
                        .IsUnique();

                    b.ToTable("reflexiones_mejora", (string)null);
                });

            modelBuilder.Entity("AnalisisIA", b =>
                {
                    b.HasOne("BackendParaPlataforma.Entities.Emociones", "Emociones")
                        .WithMany("AnalisisIAs")
                        .HasForeignKey("Emocion_Detectada_IA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendParaPlataforma.Entities.DiarioEmocional", "DiarioEmocional")
                        .WithOne("AnalisisIA")
                        .HasForeignKey("AnalisisIA", "Id_Diario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiarioEmocional");

                    b.Navigation("Emociones");
                });

            modelBuilder.Entity("BackendParaPlataforma.Entities.DiarioEmocional", b =>
                {
                    b.HasOne("BackendParaPlataforma.Entities.Emociones", "Emocion")
                        .WithMany("DiariosEmocionales")
                        .HasForeignKey("Id_Emocion_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendParaPlataforma.Entities.Usuario", "Usuario")
                        .WithMany("Diarios")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emocion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackendParaPlataforma.Entities.ProgresoModuloUsuario", b =>
                {
                    b.HasOne("BackendParaPlataforma.Entities.Usuario", "Usuario")
                        .WithMany("ProgresosModulos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProgresoUsuario", b =>
                {
                    b.HasOne("BackendParaPlataforma.Entities.Usuario", "Usuario")
                        .WithMany("ProgresosUsuarios")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ReflexionMejora", b =>
                {
                    b.HasOne("BackendParaPlataforma.Entities.DiarioEmocional", "DiarioEmocional")
                        .WithOne("ReflexionMejora")
                        .HasForeignKey("ReflexionMejora", "Id_Diario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiarioEmocional");
                });

            modelBuilder.Entity("BackendParaPlataforma.Entities.DiarioEmocional", b =>
                {
                    b.Navigation("AnalisisIA");

                    b.Navigation("ReflexionMejora");
                });

            modelBuilder.Entity("BackendParaPlataforma.Entities.Emociones", b =>
                {
                    b.Navigation("AnalisisIAs");

                    b.Navigation("DiariosEmocionales");
                });

            modelBuilder.Entity("BackendParaPlataforma.Entities.Usuario", b =>
                {
                    b.Navigation("Diarios");

                    b.Navigation("ProgresosModulos");

                    b.Navigation("ProgresosUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
